### PR TITLE
Interface for Variables

### PR DESCRIPTION
**Pull request by tomitrescak**
I have implemented a simple yet useful interface for watching Python Variables from VS CODE.
Features:

- Show all defined variables
- Show / Hide Variable content
- Automatically update variable content after code run
- Pin (watch) variables, useful when optimising a specific value or when comparing results in two variables 
- Visualise true / false values in color

Here is a DEMO gif:

pythinvariables

KNOWN ISSUES:
- Optimisation could be smarter, sending only changed variables
- First variables are sent after 500ms delay, as for some reason socket is incorrectly mixing variable updates with code result calls
- Lines of dataset are limited to 500 and array elements to 10.000. This is hardcoded, should be probably configurable via VS Code config option

### CODE REVIEW

**Comment by DonJayamanne** [comment]
I'll look into this PR soon, looks awesome. Thanks

**Comment by tomitrescak** [comment]
Good news ;) I am using it a lot, hopefully others will find it useful.

**Comment by hambez** [comment]
This looks great, really useful. Has this feature been included in the latest version on the marketplace? If so is there anything I need to configure to get it working?

**Comment by DonJayamanne** [comment]
@tomitrescak I'd like to publish the new version. Unfortunately it doesn't seem to be working in master. 
Please could you check it out. Thanks

**Comment by Oulander** [comment]
Super excited to get this, thanks a million @tomitrescak and @DonJayamanne for the great work!

**Comment by tomitrescak** [comment]
@DonJayamanne, how can we help to get the new version out? thanks.

**Comment by Frawzey** [comment]
Hi, any update on this? @DonJayamanne @tomitrescak

**Comment by Frawzey** [comment]
I moved from PyCharm to VS Code because its light and faster. Now I have to move back? 👎

**Comment by tomitrescak** [comment]
@Frawzey you do not have to do anything ... that's what I did. I submitted the PR here to have a better tooling for Python. You are welcome to contribute as well.

**Comment by alex-delacruz** [comment]
Not working

**Comment by tomitrescak** [comment]
@alex-Delacruz you just won the contest for the most useless comment on github.

**Pull request merged**
