### PR TITLE
Visual improvements on result view

### PR DESCRIPTION
**Pull request by neilsustc**
1. remove margin/padding of body. related #62
2. vertically align checkbox
3. add a space between checkbox and clear button. related #57

image

### CODE REVIEW

**Comment by neilsustc** [comment]
@DonJayamanne Just two minutes 😉

**Comment by neilsustc** [comment]
Any updates 😳

**Comment by Louis-udm** [comment]
and adapt the colour for the dark theme.
https://github.com/DonJayamanne/vscodeJupyter/issues/87

**Comment by DonJayamanne** [comment]
>and adapt the colour for the dark theme.
No, separate PR for that.

**Comment by DonJayamanne** [comment]
@neilsustc I'll test and merge the PR today, thanks.

**Comment by zachguo** [comment]
Is there a way to make checkbox and button fixed to top?

**Comment by piox34** [comment]
Was this merged? Would be great to remove the vertical  scrollbar and just fold text.

**Pull request merged**
